version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "127.0.0.1:${DB_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - "db-data:/data/db"

volumes:
  db-data: {}
  